server:
  port: 8080

spring:
  application:
    name: limit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/limit
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none

limit:
  sum: 10000
  scheduled:
    cron: "0 0 * * * *"


